### ISSUE TITLE
generateDbScript.py fails to run

### ISSUE THREAD

**Issue by yoid2000** [gda-score/code#25]
Running generateDbScript.py generated the error shown below.

After you've refactored (issue #24), please do a pull request so that we can handle the bugs in that. Also of course try to do a bit more testing....

```
PS C:\Users\francis\Documents\GitHub\code\utility> py generateDbScript.py paulDbBankingAccounts.json
Traceback (most recent call last):
  File "generateDbScript.py", line 3, in <module>
    from gdaUtility import gdaUtility
  File "C:\Users\francis\Documents\GitHub\code\utility\gdaUtility.py", line 12, in <module>
    from gdaScore import gdaAttack
  File "../common\gdaScore.py", line 16, in <module>
    from gdaUtilities import getInterpolatedValue
  File "../common\gdaUtilities.py", line 197
    params['flushCache'=True];
                       ^
SyntaxError: invalid syntax
PS C:\Users\francis\Documents\GitHub\code\utility>
```

**Comment by yoid2000** [comment]
@srnb I must apologize. This is my bug actually. My bad.
